### PR TITLE
Feat/account

### LINKED ISSUE #129: Support multiple accounts in BIP44 derivation path

### PR DESCRIPTION
**Pull request by isocolsky**
Fixes #129

### CODE REVIEW

**Comment by matiu** [comment]
Maybe we should add it also in

fromMnemonics
and in
CreateWithMnemonics

in this same PR... what you think?


On Mon, Oct 5, 2015 at 3:33 PM, Ivan Socolsky <notifications@github.com>
wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/bitpay/bitcore-wallet-client/pull/154
> Commit Summary
>
>    - all test passing with account 0
>    - support account arg when creating from external source
>    - v0.7.0
>
> File Changes
>
>    - *M* lib/api.js
>    <https://github.com/bitpay/bitcore-wallet-client/pull/154/files#diff-0>
>    (2)
>    - *M* lib/credentials.js
>    <https://github.com/bitpay/bitcore-wallet-client/pull/154/files#diff-1>
>    (17)
>    - *M* package.json
>    <https://github.com/bitpay/bitcore-wallet-client/pull/154/files#diff-2>
>    (4)
>
> Patch Links:
>
>    - https://github.com/bitpay/bitcore-wallet-client/pull/154.patch
>    - https://github.com/bitpay/bitcore-wallet-client/pull/154.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-wallet-client/pull/154>.
>



-- 
BitPay.com

**Comment by isocolsky** [comment]
Done!
This needs careful review as it breaks compatibility in the BWC API.
The strategy was to not assume any value by default in `credentials.js`. All params are required and checked for validity.
BWC API had some inconsistencies with arguments, especially the `network` param. Assuming default values there should be ok.

**Comment by matiu** [comment]
Great job, we need to do https://github.com/bitpay/copay/issues/3311 for the next release of Copay.

**Comment by jeshan** [comment]
hi all, are there any examples on how to use multiple accounts under one HD wallet? @isocolsky 
even high-level steps will do.

I have looked through the BWC & BWS code but never managed to figure it out.
If, for example, I tried the seedFromExtendedPrivateKey method passing in an account index like 1, then I've seen that you get different copayer ID back than the default (i.e with account index 0). But then, I'd want to use the result to create addresses and get balances. It says that it's not authorised because BWS isn't aware of this copayer ID, isn't it?


Let me know advice you have.

**Pull request merged**
