### PR TITLE
Add API.getUtxos

### PR DESCRIPTION
**Pull request by troggy**
Client to support new BWS API https://github.com/bitpay/bitcore-wallet-service/pull/292

### CODE REVIEW

**Comment by troggy** [comment]
Ok, going to add some tests

**Comment by troggy** [comment]
I suppose, test for this API will require new version of ``bitcore-wallet-service`` to be published

**Comment by isocolsky** [comment]
Published! Please use BWS v0.0.44

**Comment by troggy** [comment]
Added test. Please review

**Comment by isocolsky** [comment]
Good job, thanks!

**Pull request merged**
