### PR TITLE
use bitcore-style errors

### PR DESCRIPTION
**Pull request by gabegattis**

### CODE REVIEW

**Comment by matiu** [comment]
Could you please rebase it? we are ready to merge it.

**Comment by gabegattis** [comment]
I will take a look tomorrow.

**Comment by gabegattis** [comment]
I fixed the conflicts, but the test coverage went down. I'm trying to see how to maintain coverage

**Comment by gabegattis** [comment]
@matiu I added some new tests around the error conditions and it brought coverage up. This should be ready now.

**Comment by matiu** [comment]
Great. LGTM.

**Comment by gabegattis** [comment]
@matiu There were some additional merge conflicts. I just fixed those.

**Pull request merged**
