### PR TITLE
keep the seed imported from mnemonics

### PR DESCRIPTION
**Pull request by JDonadio**
In Copay [#3534](https://github.com/bitpay/copay/issues/3534) [#3520](https://github.com/bitpay/copay/issues/3520)

### CODE REVIEW

**Comment by dabura667** [comment]
You need to remove line from the credentials test:

https://github.com/bitpay/bitcore-wallet-client/blob/master/test/credentials.js#L193

```javascript
should.not.exist(c2.mnemonic);
```

This will pass the travis tests for you.

**Comment by tanojaja** [comment]
Updated. Thanks @dabura667 :+1:

**Comment by isocolsky** [comment]
needs rebase

**Comment by JDonadio** [comment]
Rebased

**Pull request merged**
